version: "2"

services:
  server:
    env_file:
      - .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
    ports:
      - 3000:3000
    command: python src/server.py

  dbdata:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:9.4
    volumes_from:
      - dbdata

  testserver:
    env_file: .env
    image: python:3.7
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
      POSTGRES_HOST_AUTH_METHOD: trust
    command: python -m pytest tests/

  testdb:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:9.4